// 환경변수 템플릿 파일 (GitHub에 커밋 가능)
// 실제 사용 시 이 파일을 복사하여 env.js로 변경 후 키 값을 입력하세요.
window.env = {
  VITE_FIREBASE_API_KEY: "YOUR_FIREBASE_API_KEY",
  VITE_FIREBASE_AUTH_DOMAIN: "YOUR_PROJECT_ID.firebaseapp.com",
  VITE_FIREBASE_PROJECT_ID: "YOUR_PROJECT_ID",
  VITE_FIREBASE_STORAGE_BUCKET: "YOUR_PROJECT_ID.firebasestorage.app",
  VITE_FIREBASE_MESSAGING_SENDER_ID: "YOUR_MESSAGING_SENDER_ID",
  VITE_FIREBASE_APP_ID: "YOUR_APP_ID",
  VITE_TOSS_CLIENT_KEY: "YOUR_TOSS_CLIENT_KEY"
};
